wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: password
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: password
   
Note: This will pull wordpress, mariadb and phpadmin images from the web and spin of '3' docker containers. When you want to access them, you need to use the Amazon EC2 instance
publci ip with the assigned port number.

    
    
